### ISSUE TITLE
CMake: Linking error

### ISSUE THREAD

**Issue by FlorianBen** [ess-dmsc/h5cpp#442] opened 2020-06-10 22:54 UTC
Sorry for the silly question, but I'm facing troubles when using h5cpp in my CMake project. I have the following configuration: Executable B <- Lib A <- H5CPP (Lib A links with h5cpp as public, and then executable B links Lib A). When compiling target B, I get the following error: `ld: cannot find -lhdf5`
The path to libhdf5 is no more defined for the executable B (due to this [CMake file](https://github.com/ess-dmsc/h5cpp/blob/6717ba23f8ab7eeaa9df25ff47c7bddc796e33e0/src/h5cpp/CMakeLists.txt#L35) I guess). 

I can easily fix that by importing and linking hdf5 for the target B. But, is this behavior expected? Why does h5cpp not just link libhdf5 as public?

Very comfy library, by the way.

**Comment by eugenwintersberger** [comment] 2020-06-30 19:55
This should not happen. Can you post the relevant CMake code where you perform the linking?

**Comment by FlorianBen** [comment] 2020-07-02 20:16
I uploaded a minimal working example [here](https://github.com/FlorianBen/TestH5cppLink). First, I defined a shared library that uses h5cpp:
```
set(LIB_CORE ${CMAKE_CURRENT_SOURCE_DIR}/lib.cpp)
find_package(h5cpp REQUIRED)
add_library(core SHARED ${LIB_CORE})
add_library(ns::core ALIAS core)
target_link_libraries(core PUBLIC h5cpp)
```
Then I use it for an executable target:
```
set(CLI_SRC ${CMAKE_CURRENT_SOURCE_DIR}/test.cpp)
add_executable(cli ${CLI_SRC})
target_link_libraries(cli PRIVATE ns::core)
```
During the executable compilation ld complains about `-lhdf5`

### Miscellaneous information
OS: Ubuntu 20.04
hdf5 version: 1.10.4 (from Ubuntu repo)
h5cpp version: master
h5cpp info: compiled from source without conan and installed in a local directory.

**Comment by eugenwintersberger** [comment] 2020-07-04 10:55
I tried with the current master branch to reproduce the above problem using the following simple CMake configuration 
```cmake
cmake_minimum_required(VERSION 3.7.0)
project("usingh5cpp")

find_package(h5cpp REQUIRED)
add_library(core SHARED core.cpp)
target_link_libraries(core h5cpp)

add_executable(app app.cpp)
target_link_libraries(app PRIVATE core)
```
Unfortunately this works nicely on my Debian 10 box. No linker errors.

**Comment by FlorianBen** [comment] 2020-07-05 14:28
Indeed, it works well when using a single cmake file. I set up github actions for two branches covering both cases, and I get same results. Sincerely I don't know why using add_subdirectory() leads to ld errors. Anyway I will close this issues if it is cmake related.

**Comment by eugenwintersberger** [comment] 2020-07-05 16:19
This is interesting. Just for fun I separated my project into two different directories, one for the app and one for the library. It still works just fine. I am using cmake 3.13. What cmake version are you running on your system?

**Comment by FlorianBen** [comment] 2020-07-06 09:30
I'm using cmake version 3.16.3 on my daily machine and cmake version 3.17.3 in my github actions. I enabled the verbosity in actions and I get the following with a single cmake file:
```
   [4/4] : && /usr/bin/c++     CMakeFiles/cli.dir/test.cpp.o  -o cli -L/usr/lib/x86_64-linux-gnu/hdf5/serial -Wl,-rpath,/usr/lib/x86_64-linux-gnu/hdf5/serial:/home/runner/work/TestH5cppLink/build:/usr/local/lib  libcore.so  /usr/local/lib/libh5cpp.so.0.3.3  /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.71.0  /usr/lib/x86_64-linux-gnu/libboost_system.so.1.71.0  -lhdf5  -lpthread  -lsz  -lz  -ldl  -lm && :
run-cmake action execution succeeded
```

And using add_subdirectory():
```
  [4/4] : && /usr/bin/c++     exe/CMakeFiles/cli.dir/test.cpp.o  -o exe/cli  -Wl,-rpath,/home/runner/work/TestH5cppLink/build/lib:/usr/local/lib  lib/libcore.so  /usr/local/lib/libh5cpp.so.0.3.3  /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.71.0  /usr/lib/x86_64-linux-gnu/libboost_system.so.1.71.0  -lhdf5  -lpthread  -lsz  -lz  -ldl  -lm && :
  FAILED: exe/cli 
  : && /usr/bin/c++     exe/CMakeFiles/cli.dir/test.cpp.o  -o exe/cli  -Wl,-rpath,/home/runner/work/TestH5cppLink/build/lib:/usr/local/lib  lib/libcore.so  /usr/local/lib/libh5cpp.so.0.3.3  /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.71.0  /usr/lib/x86_64-linux-gnu/libboost_system.so.1.71.0  -lhdf5  -lpthread  -lsz  -lz  -ldl  -lm && :
  /usr/bin/ld: cannot find -lhdf5
  collect2: error: ld returned 1 exit status
  ninja: build stopped: subcommand failed.
```
It seems that some `-L` or `-Wl,-rpath` flags are missing when using add_subdirectory.

**Comment by eugenwintersberger** [comment] 2020-07-18 18:45
Stupid question, I should have asked it right at the beginning, what version of h5cpp are you using?

**Comment by FlorianBen** [comment] 2020-07-19 20:14
The github action uses master and on my local machine I use a derived version from [this commit ](https://github.com/FlorianBen/h5cpp/commit/9af597140e2864610c09d7077678966355235852). So both are above the version 0.3.3

**Comment by eugenwintersberger** [comment] 2020-07-26 06:30
Ok. I guess that this is not something old. Since I currently tested with the master branch I will give this a try with the 0.3.3 Debian packages.

**Comment by jkotan** [comment] 2020-08-04 15:52
Hi,
Indeed, I've tried to compile https://github.com/FlorianBen/TestH5cppLink in  ubuntu 20.04 and deb10 and I get the same error in both cases, e.g. for deb10:

```jkotan@dellek:~/sources/TestH5cppLink/build$ cmake ../
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found suitable exact version "1.10.4") found components:  C 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jkotan/sources/TestH5cppLink/build
jkotan@dellek:~/sources/TestH5cppLink/build$ make
Scanning dependencies of target core
[ 25%] Building CXX object lib/CMakeFiles/core.dir/lib.cpp.o
[ 50%] Linking CXX shared library libcore.so
[ 50%] Built target core
Scanning dependencies of target cli
[ 75%] Building CXX object exe/CMakeFiles/cli.dir/test.cpp.o
[100%] Linking CXX executable cli
/usr/bin/ld: cannot find -lhdf5
collect2: error: ld returned 1 exit status
make[2]: *** [exe/CMakeFiles/cli.dir/build.make:88: exe/cli] Error 1
make[1]: *** [CMakeFiles/Makefile2:146: exe/CMakeFiles/cli.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

```

**Comment by jkotan** [comment] 2020-08-04 19:18
The above error is because libhdf5.so is not in the standard linux library directory e,g.

   /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so

so ld cannot find it, namely
```
jkotan@dellek:~/sources/TestH5cppLink$ ld -lhdf5 --verbose

...

==================================================
attempt to open //usr/local/lib/x86_64-linux-gnu/libhdf5.so failed
attempt to open //usr/local/lib/x86_64-linux-gnu/libhdf5.a failed
attempt to open //lib/x86_64-linux-gnu/libhdf5.so failed
attempt to open //lib/x86_64-linux-gnu/libhdf5.a failed
attempt to open //usr/lib/x86_64-linux-gnu/libhdf5.so failed
attempt to open //usr/lib/x86_64-linux-gnu/libhdf5.a failed
attempt to open //usr/lib/x86_64-linux-gnu64/libhdf5.so failed
attempt to open //usr/lib/x86_64-linux-gnu64/libhdf5.a failed
attempt to open //usr/local/lib64/libhdf5.so failed
attempt to open //usr/local/lib64/libhdf5.a failed
attempt to open //lib64/libhdf5.so failed
attempt to open //lib64/libhdf5.a failed
attempt to open //usr/lib64/libhdf5.so failed
attempt to open //usr/lib64/libhdf5.a failed
attempt to open //usr/local/lib/libhdf5.so failed
attempt to open //usr/local/lib/libhdf5.a failed
attempt to open //lib/libhdf5.so failed
attempt to open //lib/libhdf5.a failed
attempt to open //usr/lib/libhdf5.so failed
attempt to open //usr/lib/libhdf5.a failed
attempt to open //usr/x86_64-linux-gnu/lib64/libhdf5.so failed
attempt to open //usr/x86_64-linux-gnu/lib64/libhdf5.a failed
attempt to open //usr/x86_64-linux-gnu/lib/libhdf5.so failed
attempt to open //usr/x86_64-linux-gnu/lib/libhdf5.a failed
ld: cannot find -lhdf5
```
I suspect one needs to add to /usr/lib/x86_64-linux-gnu/cmake/h5cpp-0.3.3/*.cmake
an INTERFACE_LINK_DIRECTORIES variable.
(The INTERFACE_INCLUDE_DIRECTORIES variable is already there)

**Comment by eugenwintersberger** [comment] 2020-08-05 08:59
Ok. This makes sense. However, it also leaves me with two problems: 
1. shouldn't that path be part of the exported target (otherwise why would I need that at all)
2. why can't I reproduce this (I will try again with the source file mentioned above)?

**Comment by jkotan** [comment] 2020-08-05 09:28
ad 1) usually ld find the library automatically but it looks like for libhdf5 it is more complicated and we have to provide additional information
ad 2) probably in your case 

ld -lhdf5 --verbose 

finds the hdf5 somewhere else.

**Comment by yuelongyu** [comment] 2020-08-05 10:15
@eugenwintersberger 2) could it be you have changed the env LD_LIBRARY_PATH?

**Comment by jkotan** [comment] 2020-08-05 11:47
Hello @FlorianBen, 
I've update ubuntu 20.04  (0.3.3-3+ub2004u1~fsec) and debian 10 (0.3.3-2+deb10u1~fsec) packages with the proposed patch (https://github.com/ess-dmsc/h5cpp/pull/447) so if you use our HDRI repository you can upgrade them. 
Now, your test works fine.
Thanks for your raport.

**Comment by FlorianBen** [comment] 2020-08-05 18:39
Indeed it works well for me now. 
May I close this issue?

**Comment by jkotan** [comment] 2020-08-05 18:47
Yes. I will close it.

**Closed by jkotan** 2020-08-05 18:47 UTC
