### ISSUE TITLE
question behavior on file close

### ISSUE THREAD

**Issue by yuelongyu** [ess-dmsc/h5cpp#311] opened 2018-06-01 14:14 UTC
Hi,

We have a program (tango device server) which takes data and save to nexus(HDF5).  During closing file, the file.close() is called. Then if I try to open the file, error ("like cannot open file") occurs. Afterwards, I added additional code and closed all the fields manually. Then it works without problem. 

My question is before the file is closed, do all the fields need to be closed explicitly? To my understanding, the file object should hold the information of the fields and call the destructor of the field 
when the file.close() is called.

**Comment by eugenwintersberger** [comment] 2018-06-04 05:57
This is unfortunately expected behaviour and is something that is a *feature* of the HDF5 C-API. If any of the objects associated with a file is still open during a file close call the file is not closed but more or less *marked* for closing. The close operation will then be executed when all associated objects are closed. If I recall correctly one can change this behaviour during file creation. However,  I personally would go for closing all children of a file first and than perform the close operation. This is the clean way how to do things.

**Comment by jkotan** [comment] 2018-06-15 06:19
I add this bug report to this issue because it is somehow related. It looks like that insead of close() command in some cases one has to use destructor which is weird, e.g.

    #include <h5cpp/hdf5.hpp>
    #include <iostream>



    int main()
    {
      { // without this bracket works

	hdf5::file::File nexus_file = hdf5::file::create("closetest.nxs");
	hdf5::node::Group root_group = nexus_file.root();

	std::string hdf5_version =  "1.0.0";
	auto type = hdf5::datatype::create<std::string>();
	hdf5::dataspace::Scalar space;

	root_group.attributes.create("HDF5_version",type,space).write(hdf5_version);

	nexus_file.close();

      } // without this bracket works


      auto file2 = hdf5::file::open("closetest.nxs", hdf5::file::AccessFlags::READONLY);
      auto r2 = file2.root();

      //  { // with this bracket works

      auto attr = r2.attributes[0];
      std::cout<<attr.name()<<std::endl;

      // } // with this bracket works

      r2.close();
      file2.close();


      auto file3 = hdf5::file::open("closetest.nxs", hdf5::file::AccessFlags::READWRITE);

      file3.close();
      return 0;

    }

causes

    HDF5_version
    HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 139978880916352:
      #000: ../../../src/H5F.c line 579 in H5Fopen(): unable to open file
	major: File accessibilty
	minor: Unable to open file
      #001: ../../../src/H5Fint.c line 1137 in H5F_open(): file is already open for read-only
	major: File accessibilty
	minor: Unable to open file
    terminate called after throwing an instance of 'std::runtime_error'
      what():  Failure opening file ["closetest.nxs"]
    Aborted

However, when you add the brackets to  the attribute read statement (denoted in the code) or remove brackets from the attribute write statement (in the code) you do not get the error. Something is messed up.

**Comment by jkotan** [comment] 2018-06-15 06:54
The first bracket can be exchanged by close statement, i.e. when you do not close the root_group it works:

    #include <h5cpp/hdf5.hpp>
    #include <iostream>



    int main()
    {

      hdf5::file::File nexus_file = hdf5::file::create("closetest.nxs");
      std::string hdf5_version =  "1.0.0";
      auto type = hdf5::datatype::create<std::string>();
      hdf5::dataspace::Scalar space;
      
      
      hdf5::node::Group root_group = nexus_file.root();
      root_group.attributes.create("HDF5_version", type, space).write(hdf5_version);
      
      // without this line works
      root_group.close();
      
      nexus_file.close();


      auto file2 = hdf5::file::open("closetest.nxs", hdf5::file::AccessFlags::READONLY);
      auto r2 = file2.root();

      //  { // with this bracket works

      auto attr = r2.attributes[0];
      std::cout<<attr.name()<<std::endl;

      // } // with this bracket works

      r2.close();
      file2.close();


      auto file3 = hdf5::file::open("closetest.nxs", hdf5::file::AccessFlags::READWRITE);

      file3.close();
      return 0;


    }

**Comment by martukas** [comment] 2018-06-15 10:50
Well, `attr` also had to be closed. When you added brackets, that created another scope, which, once you left, RAII took care of closing `attr` for you. And that makes sense.

I don't quite get why you go around closing these explicitly. Yes, destructors are there to help you. This is why we have RAII, so you don't have to explicitly close anything. In all of our tested scenarios, we never use the close function except for when we purposefully try to provoke pathological behavior, i.e. to provoke exception throws. I was even tempted to at some point to make the `close()` functions private... In any case I would suggest you use it while imagining that the `close()` function does not exist. If an object is alive, then it is sitting on a resource. Kind of like a mutex. You want it released? You destroy it.

In the way this library works, your only duty is to keep the file open in your scope (or higher scope) while you do anything with the objects within it. You can extract structures deeper in the tree and feel free to discard any intermediate groups you had to traverse to find them, allowing them to die off as you leave various scopes. So long as the file is the last thing that goes out of scope and closes itself, everything else should work.

So, for scenarios like this, where you are opening and closing the same file multiple times, I would rather say create separate functions for each step of the process. A function to create and initially populate the file and then a separate one to reopen it with  SWRM or something. That way you will avoid such clashes.

The bahevior related to closing or not closing the `root_group` is a bit more puzzling. Might be underlying HDF5 behavior? We should look into this.

But you can avoid this problem for now if you follow the more piecemeal architectural approach above.

**Comment by jkotan** [comment] 2018-06-15 11:11
The example was based on the code from `libpniio` from @eugenwintersberger.  I get the error in python from `python-pninexus` that's why I decide to reproduce it in c++. 

From python point of view `close` method is quite useful because destructors are usually invoked by garbage collector. 

In python creating a separate function does not help because of the reference counter.

Well, closing `attr` does not help.  You have to  destroy it.

**Comment by martukas** [comment] 2018-06-15 11:38
Ok, that is definitely bizarre. Probably a bug, because I don't see why this behavior should differ. Could you replicate this behavior by creating some more fine-grained test scenarios in the `test/attribute` directory? If we can start with failing tests, then we can target the problem.

**Comment by martukas** [comment] 2018-06-15 11:39
Oh, or I guess you don't have collaboration rights here. Should I try to add you guys? Or would you rather wait for me to get to this on my own time? I'm a bit preoccupied until mid next-week.

**Comment by jkotan** [comment] 2018-06-15 11:42
It would be nice to be in collaboration.

**Comment by martukas** [comment] 2018-06-15 11:48
I have put in a request. Should have it soon.

**Comment by jkotan** [comment] 2018-06-15 11:48
Thanks.

**Comment by yuelongyu** [comment] 2018-06-15 11:51
Thanks.

**Comment by martukas** [comment] 2018-06-15 11:56
Do you guys use Slack for instant chat or do you prefer something else? Also, you would not now have access to our Jenkins servers to stop/restart jobs, but you can at least look at everything:
https://jenkins.esss.dk/dm/job/ess-dmsc/job/h5cpp/
if you do need access, we can probably make that happen as well

**Comment by martukas** [comment] 2018-06-15 11:59
I guess we don't really have collaboration guidelines, but the main things I would mention are:
* name branches after the issues
* make sure it builds and tests on jenkins
* do a pull request to merge to master and get it reviewed

**Comment by yuelongyu** [comment] 2018-06-15 12:12
Yes, I have slack account. Can you please post an invitation link?

**Comment by martukas** [comment] 2018-06-15 13:02
I think it wants emails to generate invites. Can you send me your email addresses to martin.shetty@esss.se ?

**Comment by jkotan** [comment] 2018-06-19 12:06
We had requests from our users to allows close the file with the H5F_CLOSE_STRONG flag. It may be implemented in a few ways: 
1) as a additional method, e.g. closeall()
2) additional parameter in file::open()
3) additional parameter in file::close()

What do you think?

**Comment by jkotan** [comment] 2018-06-22 19:08
I've  just realized that it should be possible to set H5F_CLOSE_STONG property during creating or opening the file via fapl parameter. So 2) should works.

**Comment by martukas** [comment] 2018-06-22 21:44
@jkotan does this mean we can close the ticket?

**Comment by jkotan** [comment] 2018-06-23 07:04
No. Closing attribute in non strong mode does not work anyhow.

**Comment by jkotan** [comment] 2018-06-27 13:09
Also STRONG mode does not help for the above attribute bug, i.e.


    #include <h5cpp/hdf5.hpp>
    #include <iostream>



    int main()
    {
      hdf5::property::FileAccessList fapl;
      fapl.close_degree(hdf5::property::CloseDegree::STRONG);
      hdf5::file::AccessFlagsBase flags;
      hdf5::property::FileCreationList fcpl;
      hdf5::file::File nexus_file = hdf5::file::create("closetest.nxs", hdf5::file::AccessFlags::TRUNCATE, fcpl, fapl);
      std::string hdf5_version =  "1.0.0";
      auto type = hdf5::datatype::create<std::string>();
      hdf5::dataspace::Scalar space;


      hdf5::node::Group root_group = nexus_file.root();
      root_group.attributes.create("HDF5_version", type, space).write(hdf5_version);

      // without this line works
      root_group.close();

      nexus_file.close();


      auto file2 = hdf5::file::open("closetest.nxs", hdf5::file::AccessFlags::READONLY, fapl);
      auto r2 = file2.root();

      //  { // with this bracket works

      auto attr = r2.attributes[0];
      std::cout<<attr.name()<<std::endl;
      attr.close();
      // } // with this bracket works

      r2.close();
      file2.close();

      auto file3 = hdf5::file::open("closetest.nxs", hdf5::file::AccessFlags::READWRITE, fapl);

      file3.close();
      return 0;
    }

gives

    HDF5_version
    HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 140143531137920:
      #000: ../../../src/H5F.c line 579 in H5Fopen(): unable to open file
	major: File accessibilty
	minor: Unable to open file
      #001: ../../../src/H5Fint.c line 1137 in H5F_open(): file is already open for read-only
	major: File accessibilty
	minor: Unable to open file
    terminate called after throwing an instance of 'std::runtime_error'
      what():  Failure opening file ["closetest.nxs"]
    Aborted

**Closed** 2018-07-01 17:47 UTC
Labels: bug
