### ISSUE TITLE
Option to build without unittests

### ISSUE THREAD

**Issue by clarelspies** [ess-dmsc/h5cpp#406] opened 2019-04-24 16:29 UTC
Hello, i'm seacherd for but cant find a option to build without the unittests. The reason for this is that i dont want to usar system installed googletest. How could i proced with conan to avoid building h5cpp unit tests?

**Comment by eugenwintersberger** [comment] 2019-04-27 17:17
I will have a look on this.

**Comment by eugenwintersberger** [comment] 2019-04-27 17:51
I had a look on the problem. If `gtest` is not installed on your system `cmake` will issue a warning that it could not find the library. However, this will not break the library build. The shared object will still be built. The tests are built when invoking the `run_tests` target. At list this is how it works on my systems. Can you try this solution?

**Comment by clarelspies** [comment] 2019-04-27 23:55
When i run the command "cmake .. -DCONAN=DISABLE", i get the following error message:

`-- Could NOT find GTest (missing: GTEST_INCLUDE_DIR) 
-- Attempting to apply Debian fix for googletest
CMake Error at cmake/FindGTestFix.cmake:31 (add_subdirectory):
  The source directory

    /usr/src/gtest

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:73 (include)


-- Cannot enable coverage for target: unit_tests. Code coverage not enabled (COV=0).
-- Configuring incomplete, errors occurred!


I'm must have googletest installed? i cant build without testes? its will only be a dependency for my project

**Comment by clarelspies** [comment] 2019-04-27 23:58
In online doc i found this:

Requirements
In order to build the code you need

a C++ compiler with reasonable C++11 support (gcc>=4.9,Micrsoft Developer Studio >= 2015)
the Boost libraries
the HDF5 C library
googletest to build the unit tests
sphinx (with python) and doxygen for the documentation build
cmake >= 3.0

The issue is that i'm trying to build without the unit tests, how do i proceed?

**Comment by eugenwintersberger** [comment] 2019-06-06 20:53
Sorry for my late reply. This is somehow strange. What system you are Linux distribution are you using?

**Comment by eugenwintersberger** [comment] 2019-06-13 20:56
I cannot reproduce this issue. So I will close this for the time being.

**Closed by eugenwintersberger** 2019-06-13 20:56 UTC
